// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reznzrhygvxdkxbvwwwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlem56cmh5Z3Z4ZGt4YnZ3d3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNDAxNTksImV4cCI6MjA1MTYxNjE1OX0.8TMjl3t_3ofwnl-QpiDgo8r8p4lT6hl-onR9LVB06TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);